config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :storages
  resources :tags
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'index#index'
  get '/public/:page' => 'application#access_public'
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    get '/' => 'index#index'
    resources :items
    resources :storages
    resources :tags
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include ActiveStorageSupport::SupportForBase64

  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_base64_attached :image
  has_and_belongs_to_many :tags
  belongs_to :storage

  validates :name, :image, presence: true
  validates :count, :price, numericality: { only_integer: true }

  scope :has_tags, -> (tags) {
    joins(:tags)
    .where(tags: {id: tags})
    .select("items.*, count(tags.id) as tags")
    .group(:id)
    .having("tags >= ?", tags.length)
  }
end

app/models/storage.rb
class Storage < ApplicationRecord
  has_many :items
  belongs_to :parent, :class_name => "Storage", optional: true
  has_many :children, :class_name => "Storage", :foreign_key => 'parent_id'

  validates :name, presence: true

  scope :top_level, -> {where(:parent_id => nil)}
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :items
  belongs_to :parent, :class_name => "Tag", optional: true
  has_many :children, :class_name => "Tag", :foreign_key => 'parent_id'

  validates :name, presence: true

  scope :top_level, -> {where(:parent_id => nil)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def access_public
    render file: "public/#{params[:page]}.html"
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    # console
    if search_params
      all_items = Item.where "items.name like ?", "%#{search_params}%"
    else
      all_items = Item.all
    end
    if filter_params
      all_items = all_items.has_tags filter_params
    end
    @max_page = (all_items.length + 19) / 20
    if page_params
      @items = all_items.limit(20).offset(20*(page_params.to_i-1))
    else
      @items = all_items
    end
    params[:test] = "test"
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    # base64 gem expecting {data: 'data:...'} parameter
    params[:item][:image] = {:data => params[:item][:image]}
    @item = Item.new(item_params)
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        # TODO error when duplicate
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      # TODO update with other information doesn't work?
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :count, :price, :storage_id, :time_in, :time_out,
        tag_ids: [], image: :data)
    end
    def page_params
      params.fetch(:page, '1')
    end
    def search_params
      params.fetch(:name, nil)
    end
    def filter_params
      params.fetch(:tag_filters, nil)
    end
end

app/controllers/storages_controller.rb
class StoragesController < ApplicationController
  before_action :set_storage, only: [:show, :edit, :update, :destroy]

  # GET /storages
  # GET /storages.json
  def index
    # @storages = Storage.all
    @top_levels = Storage.top_level
  end

  # GET /storages/1
  # GET /storages/1.json
  def show
  end

  # GET /storages/new
  def new
    @storage = Storage.new
  end

  # GET /storages/1/edit
  def edit
  end

  # POST /storages
  # POST /storages.json
  def create
    @storage = Storage.new(storage_params)

    respond_to do |format|
      if @storage.save
        format.html { redirect_to @storage, notice: 'Storage was successfully created.' }
        format.json { render :show, status: :created, location: @storage }
      else
        format.html { render :new }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /storages/1
  # PATCH/PUT /storages/1.json
  def update
    respond_to do |format|
      if @storage.update(storage_params)
        format.html { redirect_to @storage, notice: 'Storage was successfully updated.' }
        format.json { render :show, status: :ok, location: @storage }
      else
        format.html { render :edit }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /storages/1
  # DELETE /storages/1.json
  def destroy
    @storage.destroy
    respond_to do |format|
      format.html { redirect_to storages_url, notice: 'Storage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_storage
      @storage = Storage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def storage_params
      params.require(:storage).permit(:name, :parent_id)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    # @tags = Tag.all
    @top_levels = Tag.top_level
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :parent_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/index/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Home Inventory</h1>

<table class='large-text'>
  <thead>
    <tr>
      <th><%= link_to 'Items', items_path %></th>
      <th><%= link_to 'Storages', storages_path %></th>
      <th><%= link_to 'Tags', tags_path %></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= Item.count %></td>
      <td><%= Storage.count %></td>
      <td><%= Tag.count %></td>
    </tr>
    <tr>
      <% [Item,Storage,Tag].each do |c| %>
        <td>
          <% c.last(5).each do |ele| %>
            <div><%= ele.name %></div>
          <% end %>
        </td>
      <% end %>
    </tr>
    <tr>
      <td><%= link_to 'New Item', new_item_path, class: 'link_button' %></td>
      <td><%= link_to 'New Storage', new_storage_path, class: 'link_button' %></td>
      <td><%= link_to 'New Tag', new_tag_path, class: 'link_button' %></td>
    </tr>
  </tbody>
</table>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% item = Item.find(params[:format]) if params[:format] %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :count %>
    <%= form.number_field :count %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label 'choose_image', class: 'link_button' %>
    <label id='file_label'>No file chosen...</label>
    <%= form.hidden_field :image, value: '' %>
    <%= form.file_field 'choose_image', accept: "image/*", capture: "camera", style: 'display: none' %>
  </div>

  <div class="field">
    <label>Storage (Choose One)</label>
    <% if params[:format] %>
      <p><%= item.storage.name %></p>
      <%= form.hidden_field :storage_id, value: item[:storage_id] %>
    <% else %>
      <%= render :partial => "shared/tree",
            :locals => {:id => 'storage', :type => :radio, :name => :storage_id, :form => form, :roots => Storage.top_level} %>
      <%= link_to 'New Storage', new_storage_path %>
    <% end %>
  </div>

  <div class="field">
    <label>Tags (Miltiple Selection)</label>
    <% if params[:format] %>
      <% item.tags.each do |tag| %>
        <p><%= tag.name %></p>
        <%= form.hidden_field :tags, value: tag.id, multiple: true %>
      <% end %>
    <% else %>
      <%= render :partial => "shared/tree",
            :locals => {:id => 'tag', :type => :checkbox, :name => :tag_ids, :form => form, :roots => Tag.top_level} %>
      <%= link_to 'New Tag', new_tag_path %>
    <% end %>
  </div>

  <div class="field" style="display: none">
    <%= form.label :time_in %>
    <%= form.datetime_select :time_in %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>
<%= form_with url: items_path, method: :get, local: true do |form| %>

  <% form.instance_variable_set :@checked_list, params.permit(:search, tag_filters: []) %>
  <%= form.search_field :name, placeholder: 'Enter item name here', value: params[:name] %>
  <ul class="treeUL">
    <li class='nested'>
      <label><span class="caret">Tag filters</span></label>
      <%= form.submit 'apply', name: nil %>
      <%= render :partial => "shared/tree",
            :locals => {:type => :checkbox, :name => :tag_filters, :form => form, :roots => Tag.top_level} %>
    </li>
  </ul>

<% end %>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Count</th>
      <th>Price</th>
      <th>Image</th>
      <th>Storage</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.count %></td>
        <td><%= item.price %></td>
        <td>
          <% if item.image.attached? %>
            <img src="<%= url_for item.image %>", class='thumbnail'>
          <% end %>
        </td>
        <td><%= item.storage.name %></td>
        <td>
          <% item.tags.each do |tag| %>
            <%= tag.name %>
          <% end %>
        </td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="page_nav">
  <% page = params.fetch(:page, "1").to_i %>
  <% params.delete :search if params[:search] == '' %>
  <div>
    <%= link_to 'Prev', items_path(params.merge({:page => "#{[1,page-1].max}"}).permit(:search, :page, :tag_filters => [])) %>
  </div>
  <div class="page_nav_number">
    <a><%= "#{page}/#{@max_page}" %></a>
  </div>
  <div>
    <%= link_to 'Next', items_path(params.merge({:page => "#{[page+1,@max_page].min}"}).permit(:search, :page, :tag_filters => [])) %>
  </div>

</div>


<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Count:</strong>
  <%= @item.count %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Storage:</strong>
  <%= @item.storage.name %>
</p>

<p>
  <strong>Tags:</strong>
  <% @item.tags.each do |tag| %>
    <%= tag.name %>
  <% end %>
</p>

<% if @item.image.attached? %>
  <img src="<%= url_for @item.image %>">
<% end %>

<p>
  <strong>Time in:</strong>
  <%= @item.time_in %>
</p>

<p>
  <strong>Time out:</strong>
  <%= @item.time_out %>
</p>

<p>
  <%= link_to 'Edit', edit_item_path(@item) %> |
  <%= link_to 'Back', items_path %> |
  <%= link_to 'Duplicate', new_item_path(@item) %>
</p>

<p>
  <%= link_to 'Destroy', @item, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HI</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- responsive -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- ios web app -->
    <%= favicon_link_tag 'icon.png' %>
    <%= favicon_link_tag 'icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
    <%= favicon_link_tag 'icon.png', rel: 'bookmark', type: 'image/png' %>
    <meta name="apple-mobile-web-app-title" content="HI">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="full-screen" content="true">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="topnav">
      <%= link_to 'Home', root_path %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_nested_tree.html.erb
<% builder = -> (*args) { %>
  <% if type == :checkbox %>
    <% if form.instance_variable_defined? :@checked_list %>
      <% form.check_box args[0], { multiple: true, id: "#{args[0]}_#{args[1]}", checked: form.instance_variable_get(:@checked_list).fetch(:tag_filters, []).include?(args[1].to_s) }, args[1], nil %>
    <% else %>
      <% form.check_box args[0], { multiple: true, id: "#{form.object_name}_#{args[0]}_#{args[1]}" }, args[1], nil %>
    <% end %>
  <% else %>
    <% form.radio_button *args %>
  <% end %>
<% } %>

<% if node.children.length > 0 %>
  <li class='nested'>
  <%= builder.call name, node.id %>
  <%= form.label "#{name}_#{node.id}" do %>
    <span class="caret"><%= node.name%></span>
  <% end %>
  <ul>
    <% node.children.each do |child|%>
      <%= render :partial => "shared/nested_tree", :locals => {:type => type, :name => name, :form => form, :node => child} %>
    <% end %>
  </ul>
<% else %>
  <li>
  <%= builder.call name, node.id %>
  <%= form.label "#{name}_#{node.id}" do %>
    <%= node.name%>
  <% end %>
<% end %>
  </li>

app/views/shared/_tree.html.erb
<input type="text"
  id="search_input<%= local_assigns[:id] ? "_#{local_assigns[:id]}": ''%>" 
  placeholder="Search for ..."
>
<ul class="treeUL">
  <% roots.each do |root| %>
    <%= render :partial => "shared/nested_tree",
      :locals => {:type => type, :name => name, :form => form, :node => root} %>
  <% end %>
</ul>

app/views/storages/_form.html.erb
<%= form_with(model: storage, local: true) do |form| %>
  <% storage = Storage.find(params[:format]) if params[:format] %>
  <% if storage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(storage.errors.count, "error") %> prohibited this storage from being saved:</h2>

      <ul>
        <% storage.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <label>Parent (Choose One)</label>
    <% if params[:format] %>
    <% #TODO style for parent %>
      <p><%= storage.parent ? storage.parent.name : '' %></p>
      <%= form.hidden_field :parent_id, value: storage[:parent_id] %>
    <% else %>
      <%= render :partial => "shared/tree",
            :locals => {:type => :radio, :name => :parent_id, :form => form, :roots => Storage.top_level} %>
      <input type="button" value="Reset"
        onclick="document.querySelector('input[type=radio]:checked').checked=false">
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/storages/edit.html.erb
<h1>Editing Storage</h1>

<%= render 'form', storage: @storage %>

<%= link_to 'Show', @storage %> |
<%= link_to 'Back', storages_path %>

app/views/storages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Storages</h1>

<%= form_with(model: @top_levels.first, local: true) do |form| %>
  <%= render :partial => "shared/tree",
        :locals => {:type => :radio, :name => :parent_id, :form => form, :roots => @top_levels} %>
<% end %>

<p>
  <%= link_to 'Show', storage_path('0'), class: 'mutable_link link_button' %>
  <%= link_to 'Edit', edit_storage_path('0'), class: 'mutable_link link_button' %>
  <%= link_to 'Destroy', storage_path('0'), class: 'mutable_link link_button', method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

<p><%= link_to 'New Storage', new_storage_path, class: 'link_button' %></p>

app/views/storages/new.html.erb
<h1>New Storage</h1>

<%= render 'form', storage: @storage %>

<%= link_to 'Back', storages_path %>

app/views/storages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @storage.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @storage.parent ? @storage.parent.name : '' %>
</p>

<p>
  <%= link_to 'Edit', edit_storage_path(@storage) %> |
  <%= link_to 'Back', storages_path %> |
  <%= link_to 'Duplicate', new_storage_path(@storage) %>
</p>

<strong>Items Inside:</strong>
<table>
  <thead>
    <th>Name</th>
    <th>Count</th>
    <th>Image</th>
  </thead>
  <tbody>
    <% @storage.items.each do |item| %>
      <tr>
        <td><%= link_to item.name, item_path(item) %></td>
        <td><%= item.count %></td>
        <td>
          <% if item.image.attached? %>
            <img src="<%= url_for item.image %>", class='thumbnail'>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% tag = Tag.find(params[:format]) if params[:format] %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <label>Parent (Choose One)</label>
    <% if params[:format] %>
      <p><%= tag.parent ? tag.parent.name : '' %></p>
      <%= form.hidden_field :parent_id, value: tag[:parent_id] %>
    <% else %>
      <%= render :partial => "shared/tree",
            :locals => {:type => :radio, :name => :parent_id, :form => form, :roots => Tag.top_level} %>
      <input type="button" value="Reset"
        onclick="document.querySelector('input[type=radio]:checked').checked=false">
    <% end %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<%= form_with(model: @top_levels.first, local: true) do |form| %>
<%= render :partial => "shared/tree",
      :locals => {:type => :radio, :name => :parent_id, :form => form, :roots => @top_levels} %>
<% end %>

<p>
  <%= link_to 'Show', tag_path('0'), class: 'mutable_link link_button' %>
  <%= link_to 'Edit', edit_tag_path('0'), class: 'mutable_link link_button' %>
  <%= link_to 'Destroy', tag_path('0'), class: 'mutable_link link_button', method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

<p><%= link_to 'New Tag', new_tag_path %></p>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @tag.parent ? @tag.parent.name : '' %>
</p>

<p>
  <%= link_to 'Edit', edit_tag_path(@tag) %> |
  <%= link_to 'Back', tags_path %> |
  <%= link_to 'Duplicate', new_tag_path(@tag) %>
</p>

<strong>Items Associated:</strong>
<table>
  <thead>
    <th>Name</th>
    <th>Count</th>
    <th>Image</th>
  </thead>
  <tbody>
    <% @tag.items.each do |item| %>
      <!-- <p><%= item.name %></p> -->
      <tr>
        <td><%= link_to item.name, item_path(item) %></td>
        <td><%= item.count %></td>
        <td>
          <% if item.image.attached? %>
            <img src="<%= url_for item.image %>", class='thumbnail'>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>